server:
  port: 80
  servlet:
    context-path: /
    encoding:
      charset: UTF-8
      enabled: true
      force: true

spring:
  devtools:
    livereload:
      # livereload 서버 켜기
      enabled: true
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB
  datasource:
    driver-class-name: oracle.jdbc.driver.OracleDriver
    url: jdbc:oracle:thin:@db202201212242_high?TNS_ADMIN=C:/key/Wallet_DB202201212242
    username: timecoin
    password: 00780078Jsjs^^
  jpa:
    open-in-view: true
    hibernate:
      ddl-auto: update  #create/update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      use-new-id-generator-mappings: false
    show-sql: true
    properties:
      hibernate.format_sql: false
  jackson:
    serialization:
      fail-on-empty-beans: false

#ck-editor
ck-editor:
  image-upload: 
    path: /image/board/
  
